### ISSUE TITLE
报错，按照example无法使用

### ISSUE THREAD

**Issue by x1911** [17mon/nodejs#1]
buffer.js:934
    throw new RangeError('Index out of range');
    ^

RangeError: Index out of range
    at checkOffset (buffer.js:934:11)
    at Buffer.readInt32BE (buffer.js:1099:5)
    at IpFind (/Users/zz/Documents/trabajo/htdocs/dreamRent/server/core/ipip.js:45:49)
    at QueryReqWrap.callback (/Users/zz/Documents/trabajo/htdocs/dreamRent/server/core/ipip.js:69:22)
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:235:10)

**Comment by 17mon** [comment]
@x1911 请确认ip数据文件的位置 是否正确
